# Generated by Django 4.2.5 on 2023-09-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(blank=True, choices=[('Finance and Account', 'Finance and Account'), ('Faculty of Engineering ', 'Faculty of Engineering'), ('Faculty of Computing and Information System(FoCIS)', 'Faculty of Computing and Information System(FoCIS)'), ('Business school ', 'Business school'), ('Security', 'Security'), ('Library', 'Library'), ('Student Affairs', 'Student Affairs')], max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='details',
            field=models.TextField(blank=True, verbose_name='Explain in more detail'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Enter your complaint'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(blank=True, choices=[('Class Room', 'Class Room'), ('Campus', 'Campus'), ('Library', 'Library'), ('Administration', 'Administration')], default='Campus', max_length=64),
        ),
    ]
