# Generated by Django 4.2.5 on 2023-09-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_type_alter_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('Class Room', 'Class Room'), ('Campus', 'Campus'), ('Library', 'Library'), ('', 'Class Room')], default='Campus', max_length=64),
        ),
    ]
