# Generated by Django 5.0.3 on 2024-03-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(blank=True, choices=[('On Site', 'On Site'), ('Catchment Comminuty', 'Catchment Comminuty')], default='Campus', max_length=64),
        ),
    ]
