# Generated by Django 4.2.5 on 2023-09-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_remove_feedback_user_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=265),
        ),
    ]
